import { adminCookie, authenticateAdmin, canUseAdminTest, deploymentEnvironment, clearedAdminCookie, createAdminSession, isAdmin, isProductionEnvironment, json, method, rateLimit, refreshMarketRates, refreshOcrSnapshot, safeError, select, supabaseProjectHost } from "../serverless/core.js";

export default async function handler(request, response) {
  const path = request.query?.path || "";
  if (path === "login") return login(request, response);
  if (path === "logout") return logout(request, response);
  if (path === "page" || path === "test-page") { response.setHeader("content-type", "text/html; charset=utf-8"); response.setHeader("cache-control", "no-store"); response.setHeader("x-robots-tag", "noindex, nofollow"); return response.status(200).send(isAdmin(request) && (path !== "test-page" || canUseAdminTest()) ? (path === "page" ? dashboardPage() : testPageV2()) : loginPage()); }
  if (!isAdmin(request)) return json(response, 401, { error: "Admin authentication required." });
  try {
    if (path === "dashboard-summary") { if (!method(request, response, "GET")) return; return dashboardSummary(response); }
    if (path === "adviser-review-requests") { if (!method(request, response, "GET")) return; return rows(response, "adviser_review_requests", "created_at.desc", 200); }
    if (path === "analytics-events") { if (!method(request, response, "GET")) return; return rows(response, "analytics_events", "created_at.desc", 500); }
    if (path === "market-rate-snapshots") { if (!method(request, response, "GET")) return; return rows(response, "market_rate_snapshots", "created_at.desc", 200); }
    if (path === "ocr-snapshots") { if (!method(request, response, "GET")) return; return rows(response, "ocr_snapshots", "fetched_at.desc", 100); }
    if (path === "test-status") { if (!method(request, response, "GET")) return; if (!canUseAdminTest()) return json(response, 404, { error: "Not found." }); return testStatus(response); }
    if (path === "export/adviser-review-requests.csv") { if (!method(request, response, "GET")) return; return exportCsv(response, "adviser_review_requests", ["created_at", "name", "email", "phone", "preferred_contact_method", "consent_given", "referral_status", "user_notes"], "trimrate-adviser-review-requests.csv"); }
    if (path === "export/analytics-events.csv") { if (!method(request, response, "GET")) return; return exportCsv(response, "analytics_events", ["created_at", "session_id", "event_name", "page_path", "step_number", "step_name", "device_type", "referrer", "metadata"], "trimrate-analytics-events.csv"); }
    if (path === "refresh-market-rates") { if (!method(request, response, "POST")) return; if (!isProductionEnvironment()) return json(response, 403, { error: "Snapshot refresh is disabled outside production." }); return json(response, 200, { ok: true, result: await refreshMarketRates() }); }
    if (path === "refresh-ocr-snapshot") { if (!method(request, response, "POST")) return; if (!isProductionEnvironment()) return json(response, 403, { error: "Snapshot refresh is disabled outside production." }); return json(response, 200, { ok: true, result: await refreshOcrSnapshot() }); }
    return json(response, 404, { error: "Not found." });
  } catch (error) { console.error("admin", error); safeError(response); }
}

function login(request, response) { if (!method(request, response, "POST")) return; if (!rateLimit(request, 10, "admin-login")) return json(response, 429, { error: "Too many sign-in attempts. Please try again later." }); const { email, password } = request.body || {}; if (!authenticateAdmin(email, password)) return json(response, 401, { error: "Invalid email or password." }); const session = createAdminSession(); response.setHeader("set-cookie", adminCookie(session.value, session.expires)); return json(response, 200, { ok: true }); }
function logout(request, response) { if (!method(request, response, "POST")) return; response.setHeader("set-cookie", clearedAdminCookie()); return json(response, 200, { ok: true }); }
async function rows(response, table, order, limit) { return json(response, 200, { rows: await select(table, `select=*&order=${order}&limit=${limit}`) }); }
async function dashboardSummary(response) { const [events, requests, market, ocr] = await Promise.all([select("analytics_events", "select=session_id,event_name,step_number"), select("adviser_review_requests", "select=id"), select("market_rate_snapshots", "select=snapshot_date,created_at&order=created_at.desc&limit=1"), select("ocr_snapshots", "select=source_date,fetched_at&order=fetched_at.desc&limit=1")]); const pageViews = events.filter((event) => event.event_name === "page_view").length; const completed = events.filter((event) => event.step_number).reduce((counts, event) => ({ ...counts, [event.step_number]: (counts[event.step_number] || 0) + 1 }), {}); const most = Object.entries(completed).sort((a, b) => b[1] - a[1])[0]; return json(response, 200, { totalPageViews: pageViews, uniqueSessions: new Set(events.map((event) => event.session_id)).size, adviserReviewRequests: requests.length, visitorToRequestConversionRate: pageViews ? requests.length / pageViews : 0, mostCompletedStep: most ? { stepNumber: Number(most[0]), count: most[1] } : null, latestMarketRateRefresh: market[0]?.created_at || null, latestOcrRefresh: ocr[0]?.fetched_at || null }); }
async function testStatus(response) { const tables = ["market_rate_snapshots", "ocr_snapshots", "adviser_review_requests", "analytics_events"]; const results = await Promise.all(tables.map(async (table) => { try { await select(table, "select=id&limit=1"); return [table, "connected"]; } catch { return [table, "unavailable"]; } })); const tableStatus = Object.fromEntries(results); return json(response, 200, { environment: deploymentEnvironment(), database: Object.values(tableStatus).every((value) => value === "connected") ? "connected" : "unavailable", databaseProject: supabaseProjectHost(), tableStatus, buildVersion: process.env.VERCEL_GIT_COMMIT_SHA || process.env.GIT_COMMIT_SHA || "local", writesEnabled: deploymentEnvironment() === "production" || process.env.TRIMRATE_ALLOW_NONPROD_WRITES === "true" }); }
async function exportCsv(response, table, columns, filename) { const data = await select(table, "select=*&order=created_at.desc"); const cell = (value) => { const text = typeof value === "object" ? JSON.stringify(value ?? {}) : String(value ?? ""); return /[\",\n]/.test(text) ? `\"${text.replaceAll('\"', '\"\"')}\"` : text; }; response.setHeader("content-type", "text/csv; charset=utf-8"); response.setHeader("content-disposition", `attachment; filename=${filename}`); response.setHeader("cache-control", "no-store"); response.status(200).send(`${[columns.join(","), ...data.map((row) => columns.map((column) => cell(row[column])).join(","))].join("\n")}\n`); }
function loginPage() { return page(`<h1>TrimRate Admin</h1><p>Sign in to view private dashboard data.</p><form id="login"><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><button>Sign in</button><p id="error"></p></form><script>login.onsubmit=async(e)=>{e.preventDefault();const r=await fetch('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(login)))});if(r.ok)location='/admin';else error.textContent=(await r.json()).error||'Unable to sign in.'}</script>`); }
function dashboardPage() { return page(`<header><h1>TrimRate Admin</h1><button id="logout">Log out</button></header><section id="cards" class="cards"></section><p id="load-error" role="alert"></p><div class="actions"><button data-refresh="/api/admin/refresh-market-rates">Refresh market rates</button><button data-refresh="/api/admin/refresh-ocr-snapshot">Refresh OCR forecast</button>${canUseAdminTest() ? '<a href="/admin/test">Test page</a>' : ''}<a href="/api/admin/export/adviser-review-requests.csv">Export adviser requests</a><a href="/api/admin/export/analytics-events.csv">Export analytics</a></div><h2>Adviser review requests</h2><div class="scroll"><table><thead><tr><th>Created</th><th>Name</th><th>Email</th><th>Phone</th><th>Status</th></tr></thead><tbody id="requests"></tbody></table></div><h2>Analytics events</h2><div class="scroll"><table><thead><tr><th>Created</th><th>Event</th><th>Path</th><th>Step</th></tr></thead><tbody id="events"></tbody></table></div><script>const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));async function data(p){const r=await fetch(p);if(!r.ok)throw Error();return r.json()}function rows(id,list,fields){$(id).innerHTML=list.map(x=>'<tr>'+fields.map(f=>'<td>'+esc(x[f])+'</td>').join('')+'</tr>').join('')||'<tr><td colspan="5">No data yet.</td></tr>'}async function load(){try{const[s,r,e]=await Promise.all(['/api/admin/dashboard-summary','/api/admin/adviser-review-requests','/api/admin/analytics-events'].map(data));$('#cards').innerHTML=[['Page views',s.totalPageViews],['Unique sessions',s.uniqueSessions],['Review requests',s.adviserReviewRequests],['Conversion',((s.visitorToRequestConversionRate||0)*100).toFixed(1)+'%']].map(x=>'<article><small>'+esc(x[0])+'</small><strong>'+esc(x[1])+'</strong></article>').join('');rows('#requests',r.rows,['created_at','name','email','phone','referral_status']);rows('#events',e.rows,['created_at','event_name','page_path','step_number']);$('#load-error').textContent=''}catch{$('#load-error').textContent='Unable to load dashboard data. Check Preview Supabase settings or Vercel Function logs.'}}$('#logout').onclick=async()=>{await fetch('/api/admin/logout',{method:'POST'});location='/admin'};document.querySelectorAll('[data-refresh]').forEach(b=>b.onclick=async()=>{b.disabled=true;await fetch(b.dataset.refresh,{method:'POST'});b.disabled=false;load()});load()</script>`); }
function testPage() { return page(`<header><h1>TrimRate test page</h1><a href="/admin">Back to admin</a></header><p>This page is not indexed and is restricted to authenticated admins.</p><div id="status">Checking API/database connection…</div><h2>Calculation cases</h2><pre id="results"></pre><h2>Saved OCR and market-rate API status</h2><pre id="snapshots">Checking snapshots…</pre><script>const pay=(p,r,y)=>{const i=r/1200,n=y*12;return i?p*i*(1+i)**n/((1+i)**n-1):p/n};const cases=[['Single fixed',500000,5.5,30,2838.95],['Floating',350000,6,25,2255.05],['Two-tranche fixed A',300000,5,30,1610.46],['Two-tranche floating B',200000,6.25,25,1319.34],['Zero-rate edge',120000,0,10,1000]];results.textContent=cases.map(c=>{const actual=pay(c[1],c[2],c[3]);return c[0]+': '+(Math.abs(actual-c[4])<.01?'PASS':'FAIL')+' ($'+actual.toFixed(2)+')'}).join('\\n')+'\\nValidation: zero rate, fixed, floating, and multi-tranche component cases.';Promise.all([fetch('/api/admin/test-status').then(r=>r.json()),fetch('/api/ocr-snapshot/latest').then(r=>r.ok?r.json():null),fetch('/api/market-rates/latest').then(r=>r.ok?r.json():null)]).then(x=>{const s=x[0],o=x[1],m=x[2];status.textContent=s.environment.toUpperCase()+' · database '+s.database+' · build '+s.buildVersion+' · writes '+(s.writesEnabled?'enabled':'blocked');snapshots.textContent='OCR: '+(o?'PASS ('+o.current_ocr+'%, '+o.source_date+')':'UNAVAILABLE')+'\\nMarket rates: '+(m?'PASS ('+(m.rates?.length||0)+' terms, '+m.captured+')':'UNAVAILABLE')})</script>`); }
function testPageV2() { return page(`<header><h1>TrimRate test page</h1><a href="/admin">Back to admin</a></header><p>This page is not indexed and is restricted to authenticated admins.</p><div id="status">Checking API/database connection…</div><h2>Calculation cases</h2><pre id="results"></pre><h2>Saved OCR and market-rate API status</h2><pre id="snapshots">Checking snapshots…</pre><script>const pay=(p,r,y)=>{const i=r/1200,n=y*12;return i?p*i*(1+i)**n/((1+i)**n-1):p/n};const cases=[['Single fixed',500000,5.5,30,2838.95],['Floating',350000,6,25,2255.05],['Two-tranche fixed A',300000,5,30,1610.46],['Two-tranche floating B',200000,6.25,25,1319.34],['Zero-rate edge',120000,0,10,1000]];results.textContent=cases.map(c=>{const actual=pay(c[1],c[2],c[3]);return c[0]+': '+(Math.abs(actual-c[4])<.01?'PASS':'FAIL')+' ($'+actual.toFixed(2)+')'}).join('\\n')+'\\nValidation: zero rate, fixed, floating, and multi-tranche component cases.';const read=async p=>{const r=await fetch(p,{cache:'no-store'}),b=await r.json().catch(()=>({}));if(!r.ok)throw Error(p+' returned '+r.status);return b};Promise.allSettled([read('/api/admin/test-status'),read('/api/ocr-snapshot/latest'),read('/api/market-rates/latest')]).then(x=>{if(x[0].status!=='fulfilled'){status.textContent='Diagnostic failed: '+x[0].reason.message;return}const s=x[0].value,o=x[1].status==='fulfilled'?x[1].value:null,m=x[2].status==='fulfilled'?x[2].value:null;status.textContent=String(s.environment||'unknown').toUpperCase()+' · database '+s.database+' · project '+s.databaseProject+' · build '+s.buildVersion+' · writes '+(s.writesEnabled?'enabled':'blocked')+'\\nTables: '+Object.entries(s.tableStatus||{}).map(([k,v])=>k+'='+v).join(', ');snapshots.textContent='OCR: '+(o?'PASS ('+o.current_ocr+'%, '+o.source_date+')':'UNAVAILABLE (no Preview refresh)')+'\\nMarket rates: '+(m?'PASS ('+(m.rates?.length||0)+' terms, '+m.captured+')':'UNAVAILABLE (no Preview refresh)')}).catch(e=>{status.textContent='Diagnostic failed: '+e.message})</script>`); }

function page(body) { const environment = deploymentEnvironment(); const testFallback = `<script>if(location.pathname==='/admin/test'){setTimeout(()=>{const s=document.querySelector('#status');if(s&&s.textContent.startsWith('Checking'))s.textContent='Diagnostic request did not complete. Open Vercel Function logs for /api/admin/test-status and confirm the current Preview deployment uses the new environment variables.'},5000)}</script>`; return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>TrimRate Admin</title><style>body{margin:0;background:#f7f5f0;color:#1b2a22;font-family:system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:32px 20px}header{display:flex;justify-content:space-between;align-items:center}header:after{content:'${environment.toUpperCase()}';background:#173f77;color:#fff;padding:5px 9px;border-radius:999px;font-size:12px;font-weight:700}h1{margin:0 0 20px}h2{margin-top:36px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}article,form,pre,#status{background:#fff;border:1px solid #ded8cf;border-radius:12px;padding:16px}article small{display:block;color:#687269;font-weight:700;text-transform:uppercase}article strong{display:block;font-size:25px;margin-top:8px}.actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:22px}button,a{padding:10px 13px;border-radius:8px;border:1px solid #cddcd2;background:#fff;color:#1b2a22;font-weight:700;text-decoration:none;cursor:pointer}form{max-width:420px;display:grid;gap:12px}label{display:grid;gap:6px;font-weight:700}input{padding:10px;border:1px solid #cddcd2;border-radius:7px;font:inherit}.scroll{overflow:auto;background:#fff;border:1px solid #ded8cf;border-radius:12px}table{width:100%;border-collapse:collapse;min-width:620px}th,td{padding:10px;text-align:left;border-bottom:1px solid #eee;font-size:14px}th{color:#687269}#error{color:#ad432d}</style><main>${body}</main>${testFallback}</html>`; }
